# Generated by Django 4.0.6 on 2022-09-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25, null=True)),
                ('Gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'transgender')], default='Gender', max_length=50)),
                ('Class', models.CharField(max_length=25, null=True)),
                ('Father_information', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
