# Generated by Django 4.0.6 on 2022-09-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student_information',
        ),
    ]
