# Generated by Django 4.0.6 on 2022-09-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_student_student_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_information',
            new_name='Student',
        ),
    ]
