# Generated by Django 4.0.6 on 2022-09-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_rename_student_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Father_information',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Gender',
        ),
    ]
