# Generated by Django 4.0.6 on 2022-09-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_remove_students_name_students_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
