# Generated by Django 4.0.6 on 2022-09-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_studentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
