# Generated by Django 4.0.6 on 2022-09-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_studentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='description',
        ),
    ]
