# Generated by Django 4.0.6 on 2022-09-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_studentmodel_father_information_studentmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='classes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
