# Generated by Django 4.0.6 on 2022-09-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_studentmodel_classes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
