# Generated by Django 4.0.6 on 2022-09-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_alter_studentmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'transgender')], default='gender_type', max_length=50),
        ),
    ]
