# Generated by Django 4.0.6 on 2022-09-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_alter_studentmodel_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofclass', models.CharField(choices=[('1', 'finance class'), ('2', 'blockchain class'), ('3', 'commerce class'), ('3', 'other class')], default='class', max_length=50)),
                ('other_class', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
