# Generated by Django 4.0.6 on 2022-09-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='studentrecode',
        ),
    ]
